# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created',
            new_name='posted',
        ),
        migrations.AddField(
            model_name='article',
            name='Section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='articles.Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.Tag'),
        ),
    ]
