# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170316_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Section'),
        ),
    ]
