# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 07:51
from __future__ import unicode_literals

import articles.models
from django.db import migrations
import redactor.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170321_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=articles.models.upload_image_to),
        ),
    ]
