# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180117_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.Article')),
                ('a2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.Article')),
                ('a3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.Article')),
                ('a4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.Article')),
                ('a5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.Article')),
            ],
        ),
    ]
