# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180118_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='section',
            new_name='Section',
        ),
    ]
